const API='http://localhost:8080/api';const tokenKey='erp_access_token',sessionKey='erp_session';
function token(){return localStorage.getItem(tokenKey)}function session(){try{return JSON.parse(localStorage.getItem(sessionKey)||'null')}catch(_){return null}}function isFinanceUser(){return['SUPER_ADMIN','ADMIN','FINANCE'].includes(session()?.role)}function isProcurementUser(){return['SUPER_ADMIN','ADMIN','PROCUREMENT'].includes(session()?.role)}function canApprove(){return['SUPER_ADMIN','ADMIN'].includes(session()?.role)}
function showApp(s){document.querySelector('#loginView').classList.add('hidden');document.querySelector('#appView').classList.remove('hidden');document.querySelector('#sessionUser').textContent=`${s.username} · ${s.role}`;document.querySelector('#finance').classList.toggle('hidden',!isFinanceUser());document.querySelector('#reports').classList.toggle('hidden',!isFinanceUser());loadDashboard()}function showLogin(){document.querySelector('#loginView').classList.remove('hidden');document.querySelector('#appView').classList.add('hidden')}
async function json(url,o={}){const headers=new Headers(o.headers||{});headers.set('Accept','application/json');if(o.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');if(token())headers.set('Authorization',`Bearer ${token()}`);const r=await fetch(url,{...o,headers});if(r.status===401){localStorage.removeItem(tokenKey);localStorage.removeItem(sessionKey);showLogin();throw Error('Session expired')}if(!r.ok){let m=`API ${r.status}`;try{const b=await r.json();m=b.message||m}catch(_){}throw Error(m)}return r.status===204?null:r.json()}
async function action(url,method='PATCH',body=null){try{await json(url,{method,body:body?JSON.stringify(body):undefined});await loadDashboard()}catch(e){alert(e.message)}}
async function decideRequest(id){const decision=prompt('Enter APPROVED or REJECTED');if(!decision)return;const status=decision.trim().toUpperCase();if(!['APPROVED','REJECTED'].includes(status)){alert('Decision must be APPROVED or REJECTED');return}await action(`${API}/procurement/purchase-requests/${id}/decision`,'PATCH',{status})}
async function login(e){e.preventDefault();const m=document.querySelector('#loginMessage');m.textContent='Signing in…';try{const r=await json(`${API}/auth/login`,{method:'POST',body:JSON.stringify({username:document.querySelector('#username').value.trim(),password:document.querySelector('#password').value})});localStorage.setItem(tokenKey,r.accessToken);localStorage.setItem(sessionKey,JSON.stringify(r));showApp(r)}catch(e){m.textContent=e.message}}
async function loadDashboard(){const req=[json(`${API}/employees`),json(`${API}/departments`),json(`${API}/inventory`)];if(isProcurementUser())req.push(json(`${API}/procurement/purchase-requests/status/SUBMITTED`));if(isFinanceUser())req.push(json(`${API}/finance/payables/status/OPEN`));if(isFinanceUser())req.push(json(`${API}/reports/dashboard`));const rs=await Promise.allSettled(req),v=i=>rs[i]?.status==='fulfilled'?rs[i].value:[];const employees=v(0),departments=v(1),inventory=v(2),pending=isProcurementUser()?v(3):[],pi=isProcurementUser()?4:3,ri=isFinanceUser()?pi+1:-1,payables=isFinanceUser()?v(pi):[],report=isFinanceUser()&&rs[ri]?.status==='fulfilled'?rs[ri].value:null;document.querySelector('#employeeCount').textContent=employees.length;document.querySelector('#departmentCount').textContent=departments.length;document.querySelector('#inventoryCount').textContent=inventory.length;document.querySelector('#pendingRequests').textContent=isProcurementUser()?pending.length:'—';document.querySelector('#openPayables').textContent=isFinanceUser()?payables.length:'—';renderEmployees(employees);if(isProcurementUser())renderRequests(pending);renderInventory(inventory);if(isFinanceUser()){renderPayables(payables);renderReport(report)}}
function renderEmployees(a){const e=document.querySelector('#employeeTable');if(!a.length){e.textContent='No employees found.';return}e.innerHTML=`<table class="table"><thead><tr><th>Code</th><th>Name</th><th>Email</th><th>Status</th></tr></thead><tbody>${a.map(x=>`<tr><td>${h(x.employeeCode)}</td><td>${h(`${x.firstName} ${x.lastName}`)}</td><td>${h(x.email)}</td><td>${h(x.status)}</td></tr>`).join('')}</tbody></table>`}
function renderRequests(a){const e=document.querySelector('#procurementTable');if(!a.length){e.textContent='No submitted purchase requests.';return}e.innerHTML=`<table class="table"><thead><tr><th>ID</th><th>Employee</th><th>Vendor</th><th>Item</th><th>Qty</th><th>Price</th><th>Status</th><th>Action</th></tr></thead><tbody>${a.map(x=>`<tr><td>#${x.id}</td><td>${x.requesterEmployeeId}</td><td>${x.vendorId}</td><td>${h(x.itemDescription)}</td><td>${x.quantity}</td><td>${x.estimatedUnitPrice}</td><td>${h(x.status)}</td><td>${canApprove()?`<button onclick="decideRequest(${x.id})">Decide</button>`:'—'}</td></tr>`).join('')}</tbody></table>`}
function renderInventory(a){const e=document.querySelector('#inventoryTable');if(!a.length){e.textContent='No inventory items found.';return}e.innerHTML=`<table class="table"><thead><tr><th>SKU</th><th>Name</th><th>Unit</th><th>On hand</th><th>Unit cost</th><th>Status</th></tr></thead><tbody>${a.map(x=>`<tr><td>${h(x.sku)}</td><td>${h(x.name)}</td><td>${h(x.unit||'')}</td><td>${x.quantityOnHand}</td><td>${x.unitCost}</td><td>${h(x.status)}</td></tr>`).join('')}</tbody></table>`}
function renderPayables(a){const e=document.querySelector('#payablesTable');if(!a.length){e.textContent='No open vendor payables.';return}e.innerHTML=`<table class="table"><thead><tr><th>ID</th><th>PO</th><th>Vendor</th><th>Amount</th><th>Due</th><th>Status</th><th>Action</th></tr></thead><tbody>${a.map(x=>`<tr><td>#${x.id}</td><td>#${x.purchaseOrderId}</td><td>${x.vendorId}</td><td>${x.amount}</td><td>${x.dueDate||'—'}</td><td>${h(x.status)}</td><td>${x.status==='OPEN'?`<button onclick="action('${API}/finance/payables/${x.id}/approve')">Approve</button>`:''}${x.status==='APPROVED'?`<button onclick="action('${API}/finance/payables/${x.id}/pay')">Pay</button>`:''}</td></tr>`).join('')}</tbody></table>`}
function renderReport(r){const e=document.querySelector('#reportTable');if(!r){e.textContent='Analytics unavailable.';return}e.innerHTML=`<div class="cards report-cards"><article><small>Expense total</small><strong>${r.expenseTotal}</strong></article><article><small>Open payable value</small><strong>${r.openPayableTotal}</strong></article><article><small>Inventory value</small><strong>${r.inventoryValue}</strong></article><article><small>Purchase orders</small><strong>${r.purchaseOrderCount}</strong></article></div><p><strong>Purchase requests:</strong> ${Object.entries(r.purchaseRequestsByStatus||{}).map(([k,v])=>`${h(k)} ${v}`).join(' · ')}</p><p><strong>Purchase orders:</strong> ${Object.entries(r.purchaseOrdersByStatus||{}).map(([k,v])=>`${h(k)} ${v}`).join(' · ')}</p>`}
function h(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
document.querySelector('#loginForm').addEventListener('submit',login);['loadEmployees','refreshProcurement','refreshInventory','refreshFinance','refreshReports'].forEach(id=>document.querySelector(`#${id}`)?.addEventListener('click',loadDashboard));document.querySelector('#logout').addEventListener('click',()=>{localStorage.removeItem(tokenKey);localStorage.removeItem(sessionKey);showLogin()});const saved=session();if(token()&&saved)showApp(saved);else showLogin();
